[package]
name = "rcsh_control_core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.48", features = ["full"] }
serde_yaml = "0.9"
rcon = { version = "0.6.0", features = ["rt-tokio"] }
